#auto:        false
#server:      false
#server_port: 4000
baseurl:    /
url: http://collidoscope.de

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
#required for gitHub Pages
safe:       true
lsi:         false
pygments:    true


#markdown:    maruku
permalink:   none

prose:
  metadata:
    "_posts/blog": |
      layout:	post
      title:    "Title of your article"
      abstract: "Abstract"
      description: "SEO friendly description"
      author: "Carsten Klee"
      categories: "List of Categories"
      tags: "List of Tags"
      comments: true
      sharing: true
      published: false
    "_posts/projects": |
      layout: default
      name: "Project Name"
      img: "Project Thumbnail"
    ".": |
      layout: default
      title: "Title of the page"
      show: true
      description: "SEO friendly description"
      author: "Carsten Klee"
      weight:   5

#maruku:
#  use_tex:    false
#  use_divs:   false
#  png_engine: blahtex
#  png_dir:    images/latex
#  png_url:    /images/latex

#rdiscount:
#  extensions: []

#kramdown:
#  auto_ids: true,
#  footnote_nr: 1
#  entity_output: as_char
#  toc_levels: 1..6
#  use_coderay: false
  
#  coderay:
#    coderay_wrap: div
#    coderay_line_numbers: inline
#    coderay_line_numbers_start: 1
#    coderay_tab_width: 4
#    coderay_bold_every: 10
#   coderay_css: style